// Generated by scripts/generate-artifact-options.cjs. Artifact channel: development
package com.simulaads.reactnative
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.bridge.ReadableType
import ad.simula.ad.sdk.ads.SimulaDevOptions
internal fun configureArtifactOptions(config: ReadableMap): Boolean =
    SimulaDevOptions.configure(hidePlayableCompanion = runCatching { config.hasKey("hidePlayableCompanion") && config.getType("hidePlayableCompanion") == ReadableType.Boolean && config.getBoolean("hidePlayableCompanion") }.getOrDefault(false))
