// Generated by scripts/generate-artifact-options.cjs. Artifact channel: development
import Foundation
import SimulaAdSDK
import CoreFoundation
func configureArtifactOptions(_ config: NSDictionary) -> Bool {
    let value = config["hidePlayableCompanion"] as? NSNumber
    let hidden = value.map { CFGetTypeID($0) == CFBooleanGetTypeID() && $0.boolValue } ?? false
    return SimulaDevOptions.configure(hidePlayableCompanion: hidden)
}
