// Generated by scripts/generate-artifact-options.cjs. Artifact channel: development
/** Only present in development SDK artifacts. Requires a process restart to change. */
export interface ArtifactInitOptions { hidePlayableCompanion?: boolean; }
export function normalizeArtifactOptions(config: ArtifactInitOptions): ArtifactInitOptions {
  return config.hidePlayableCompanion === true ? { hidePlayableCompanion: true } : {};
}
