pluginManagement {
    includeBuild("../../node_modules/@react-native/gradle-plugin")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

includeBuild("../../node_modules/@react-native/gradle-plugin")

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "simula-react-native-native-test"
include(":simula-ads-react-native")
project(":simula-ads-react-native").projectDir = file("../../android")
